name: Firmware verification
on:
  push:
    branches:
      - trunk
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: [self-hosted, docker]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Build docker image
        # Build the docker image with current user's IDs so that permissions to the workspace are retained.
        run: docker build -t iida-devkit .devcontainer --build-arg USER_UID=$(id -u) --build-arg USER_GID=$(id -g)
      - name: Build firmware
        run: |
          docker run -v $PWD:/iida-devkit -w /iida-devkit iida-devkit \
          /bin/bash -c "\
            python3 -m venv .venv && source .venv/bin/activate && \
            pip install west && \
            west init . && \
            west update && \
            pip install -r zephyr/scripts/requirements.txt && \
            west zephyr-export && \
            west sdk install -t arm-zephyr-eabi && \
            west build -b iida_devkit app -- -DBOARD_ROOT=..
          "
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: Binaries
          path: |
            ./build/zephyr/zephyr.hex
          if-no-files-found: error
