name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: [self-hosted, docker]
    container:
      image: ghcr.io/sakuglumoff/iida-devkit:trunk
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    environment: release
    steps:
      - name: Build firmware
        run: |
          rm -rf /__w/iida-devkit/iida-devkit/.west /__w/iida-devkit/iida-devkit/*
          export PATH=$PATH:/github/home/.local/bin
          pip install west==1.4.0
          west init -m ${{ github.server_url }}/${{ github.repository }}.git --mr ${{ github.ref_name }}
          west update
          pip install -r zephyr/scripts/requirements.txt
          west zephyr-export
          west build -b iida_devkit application/app -- -DBOARD_ROOT=..
          mv ./build/zephyr/zephyr.hex iida_devkit.hex
      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: iida_devkit.hex
          if-no-files-found: error
      - name: Export HW design files
        run: |
          mkdir application/hardware/manufacturing
          kicad-cli sch export pdf --output iida_devkit.pdf application/hardware/iida_devkit.kicad_sch
      - name: Archive HW design files
        uses: actions/upload-artifact@v4
        with:
          name: hardware
          path: iida_devkit.pdf
          if-no-files-found: error
      - name: Build documentation
        run: |
          pip install -r application/doc/requirements.txt
          pushd application/doc
          make clean && make html
          popd
          mv application/doc/_build/html ./
      - name: Archive documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: html
          if-no-files-found: error
  release:
    needs: [build]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: hardware
          path: artifacts
      - uses: actions/download-artifact@v4
        with:
          name: firmware
          path: artifacts
      - name: Create a release
        run: |
          RELEASE_VERSION="$(echo ${GITHUB_REF_NAME} | cut -f1 -d-)"
          gh release create ${GITHUB_REF_NAME} \
            --title ${RELEASE_VERSION} \
            --draft \
            --generate-notes \
            --prerelease
          gh release upload ${GITHUB_REF_NAME} artifacts/* --clobber
